security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            http_basic: true

    access_control:
        - { path: ^/ticket/nouveau, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }